-- Entity (name)

DROP TABLE IF EXISTS `ENTITY`;
CREATE TABLE `ENTITY` (
  `ID`                 INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ENTITY_UID`         VARCHAR(50)      ,
  `COMPANY_NAME`       VARCHAR(300)              DEFAULT NULL,
  `NUM_YEARS`          INT(3)              DEFAULT 0,
  `CREATED_TS`         TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TS`        TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IN_ENTITY_UID` (`ENTITY_UID`)
) DEFAULT CHARSET = utf8;


 -- Entity Additional (Key, value

DROP TABLE IF EXISTS `ENTITY_ADDITION`;
CREATE TABLE `ENTITY_ADDITION` (
  `ID`          INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ENTITY_UID`  VARCHAR(50)         ,
  `PROP`        VARCHAR(100)              DEFAULT NULL,
  `PROP_VALUE`       TEXT              DEFAULT NULL,
  `CREATED_TS`  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TS` TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IN_ENTITY_UID` (`ENTITY_UID`),
  KEY `IN_KEY` (`PROP`)
)
DEFAULT CHARSET = utf8;



-- Categories
DROP TABLE IF EXISTS `CATEGORIES`;
CREATE TABLE `CATEGORIES` (
  `ID`          INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ENTITY_UID`  VARCHAR(50)         ,
  `CATEGORY`    VARCHAR(100)              DEFAULT NULL,
  `CREATED_TS`  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TS` TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IN_ENTITY_UID` (`ENTITY_UID`),
  KEY `IN_CATEGORY` (`CATEGORY`)
)
DEFAULT CHARSET = utf8;


-- Location(Street,city,state,zip,phone)
DROP TABLE IF EXISTS `LOCATION`;
CREATE TABLE `LOCATION` (
  `ID`          INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ENTITY_UID`  VARCHAR(50)         ,
  `LOCATION_UID`  VARCHAR(50)         ,
  `STREET`    VARCHAR(300)              DEFAULT NULL,
  `CITY`    VARCHAR(100)              DEFAULT NULL,
  `state`    VARCHAR(100)              DEFAULT NULL,
  `ZIP`    VARCHAR(20)              DEFAULT NULL,
  `PHONE`    VARCHAR(100)              DEFAULT NULL,
  `CREATED_TS`  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TS` TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IN_ENTITY_UID` (`ENTITY_UID`),
  KEY `IN_ZIP` (`ZIP`),
  KEY `IN_STATE` (`STATE`),
  KEY `IN_CITY` (`CITY`)

)
DEFAULT CHARSET = utf8;


-- operationtime (day of week, start time, end time)

DROP TABLE IF EXISTS `OPERATING_TIME`;
CREATE TABLE `OPERATING_TIME` (
  `ID`          INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `LOCATION_UID`  VARCHAR(50)         ,

  `DAY_OF_WEEK`    VARCHAR(20)              DEFAULT NULL,
  `OPEN_TIME`    TIME              DEFAULT NULL,
  `CLOSE_TIME`    TIME              DEFAULT NULL,
  `CREATED_TS`  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TS` TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IN_LOCATION_UID` (`LOCATION_UID`),
  KEY `IN_DAY_OF_WEEK` (`DAY_OF_WEEK`)
)
DEFAULT CHARSET = utf8;


-- geolocation(Latitude,longitude)


DROP TABLE IF EXISTS `GEO_LOCATION`;
CREATE TABLE `GEO_LOCATION` (
  `ID`          INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `LOCATION_UID`  VARCHAR(50)         ,
  `LONGITUDE`   FLOAT(10,6)              DEFAULT NULL,
  `LATITUDE`    FLOAT(10,6)              DEFAULT NULL,

  `CREATED_TS`  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TS` TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IN_LOCATION_UID` (`LOCATION_UID`),
  KEY `IN_LONGITUDE` (`LONGITUDE`),
  KEY `IN_LATITUDE` (`LATITUDE`)
)
DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `NOTIFICATIONS`;
CREATE TABLE `NOTIFICATIONS` (
  `ID`          				INT(10) 				UNSIGNED NOT NULL AUTO_INCREMENT,
  `ENTITY_UID`  		VARCHAR(50),
  `TYPE`        			VARCHAR(10)	DEFAULT NULL,
  `TEXT`        			TEXT              		DEFAULT NULL,
  `VALID`       			BOOLEAN          DEFAULT TRUE,
  `AGE`					INT(3)					DEFAULT 0,
  `CREATED_TS`  	TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TS` 	TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IN_ENTITY_UID` (`ENTITY_UID`)
)
DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS` (
  `ID`          		INT(10) 				UNSIGNED NOT NULL AUTO_INCREMENT,
  `FIRST_NAME`  		VARCHAR(50),
  `LAST_NAME`       VARCHAR(10)	    DEFAULT NULL,
  `EMAIL`        		VARCHAR(100)     DEFAULT NULL,
  `PASSWORD`       	VARCHAR(255)    DEFAULT NULL,
  `ACTIVE`					BOOLEAN					DEFAULT TRUE,
  `LOGGED_IN`				BOOLEAN					DEFAULT FALSE,
  `SECRET_CODE`     VARCHAR(255)    DEFAULT NULL,
  `CREATED_TS`  	  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_TS` 	  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`ID`),
  KEY `IN_EMAIL` (`EMAIL`)
)
DEFAULT CHARSET = utf8;
DROP TABLE IF EXISTS `USER_SESSION`;
CREATE TABLE `USER_SESSION` (
  `ID`          		INT(10) 				UNSIGNED NOT NULL AUTO_INCREMENT,
  `EMAIL`        		VARCHAR(100)     DEFAULT NULL,
  `ACTION`          VARCHAR(20)	    DEFAULT NULL,
  `LOG_TS`  	      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LONGITUDE`   FLOAT(10,6)              DEFAULT NULL,
  `LATITUDE`    FLOAT(10,6)              DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IN_EMAIL` (`EMAIL`)
)
DEFAULT CHARSET = utf8;
